services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: mydb
      MARIADB_USER: myuser
      MARIADB_PASSWORD: mypass
    volumes:
      - mariadb_data:/var/lib/mysql

  backend:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app # Mount current directory to /app in the container
      - /app/node_modules # Avoids conflicts with the host node_modules
    depends_on:
      - db
      - minio  # Add Minio as a dependency for the backend service
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

volumes:
  mariadb_data:
  minio_data:
